# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compareView.ui'
#
# Created: Sun Oct 13 18:20:49 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(2188, 1071)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelDatabase = QtGui.QLabel(self.centralwidget)
        self.labelDatabase.setGeometry(QtCore.QRect(60, 20, 141, 21))
        self.labelDatabase.setObjectName("labelDatabase")
        self.selectDatabase = QtGui.QComboBox(self.centralwidget)
        self.selectDatabase.setGeometry(QtCore.QRect(180, 20, 181, 27))
        self.selectDatabase.setObjectName("selectDatabase")
        self.labelFiles = QtGui.QLabel(self.centralwidget)
        self.labelFiles.setGeometry(QtCore.QRect(60, 50, 70, 21))
        self.labelFiles.setObjectName("labelFiles")
        self.dbFilesTree = QtGui.QTreeView(self.centralwidget)
        self.dbFilesTree.setGeometry(QtCore.QRect(60, 80, 771, 791))
        self.dbFilesTree.setObjectName("dbFilesTree")
        self.widCompare = QtGui.QWidget(self.centralwidget)
        self.widCompare.setEnabled(True)
        self.widCompare.setGeometry(QtCore.QRect(880, 0, 1051, 961))
        self.widCompare.setProperty("hidden", True)
        self.widCompare.setObjectName("widCompare")
        self.resultLenghtSpin = QtGui.QSpinBox(self.widCompare)
        self.resultLenghtSpin.setGeometry(QtCore.QRect(920, 40, 54, 27))
        self.resultLenghtSpin.setObjectName("resultLenghtSpin")
        self.buttonDownload = QtGui.QToolButton(self.widCompare)
        self.buttonDownload.setGeometry(QtCore.QRect(480, 900, 111, 41))
        self.buttonDownload.setObjectName("buttonDownload")
        self.tableResults = QtGui.QTableView(self.widCompare)
        self.tableResults.setGeometry(QtCore.QRect(80, 500, 901, 381))
        self.tableResults.setObjectName("tableResults")
        self.buttonCompare = QtGui.QPushButton(self.widCompare)
        self.buttonCompare.setGeometry(QtCore.QRect(490, 430, 112, 41))
        self.buttonCompare.setObjectName("buttonCompare")
        self.buttonCompare.clicked.connect(self.changeToCompare)
        self.progressBar = QtGui.QProgressBar(self.widCompare)
        self.progressBar.setGeometry(QtCore.QRect(80, 440, 951, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtGui.QLabel(self.widCompare)
        self.label.setGeometry(QtCore.QRect(90, 40, 251, 21))
        self.label.setObjectName("label")
        self.sequenceInput = QtGui.QPlainTextEdit(self.widCompare)
        self.sequenceInput.setGeometry(QtCore.QRect(80, 90, 901, 311))
        self.sequenceInput.setObjectName("sequenceInput")
        self.label_2 = QtGui.QLabel(self.widCompare)
        self.label_2.setGeometry(QtCore.QRect(730, 40, 171, 21))
        self.label_2.setObjectName("label_2")
        self.widCompare.hide()
        self.widMainMenu = QtGui.QWidget(self.centralwidget)
        self.widMainMenu.setGeometry(QtCore.QRect(880, 0, 1051, 961))
        self.widMainMenu.setObjectName("widMainMenu")
        self.buttonMenuEdit = QtGui.QToolButton(self.widMainMenu)
        self.buttonMenuEdit.setGeometry(QtCore.QRect(380, 350, 330, 45))
        self.buttonMenuEdit.setObjectName("buttonMenuEdit")
        self.buttonMenuCompare = QtGui.QPushButton(self.widMainMenu)
        self.buttonMenuCompare.setGeometry(QtCore.QRect(380, 270, 330, 45))
        self.buttonMenuCompare.setObjectName("buttonMenuCompare")
        self.buttonMenuDelete = QtGui.QToolButton(self.widMainMenu)
        self.buttonMenuDelete.setGeometry(QtCore.QRect(380, 510, 330, 45))
        self.buttonMenuDelete.setObjectName("buttonMenuDelete")
        self.buttonMenuAdd = QtGui.QToolButton(self.widMainMenu)
        self.buttonMenuAdd.setGeometry(QtCore.QRect(380, 430, 330, 45))
        self.buttonMenuAdd.setObjectName("buttonMenuAdd")
        self.buttonMenuAdd.clicked.connect(self.changeToAdd)
        self.widAddDB = QtGui.QWidget(self.centralwidget)
        self.widAddDB.setEnabled(True)
        self.widAddDB.setGeometry(QtCore.QRect(880, 0, 1051, 961))
        self.widAddDB.setProperty("hidden", True)
        self.widAddDB.setObjectName("widAddDB")
        self.buttonImport = QtGui.QPushButton(self.widAddDB)
        self.buttonImport.setGeometry(QtCore.QRect(480, 360, 112, 41))
        self.buttonImport.setObjectName("buttonImport")
        self.progressBar_2 = QtGui.QProgressBar(self.widAddDB)
        self.progressBar_2.setGeometry(QtCore.QRect(70, 570, 951, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.labelDbName = QtGui.QLabel(self.widAddDB)
        self.labelDbName.setGeometry(QtCore.QRect(80, 130, 351, 21))
        self.labelDbName.setObjectName("labelDbName")
        self.inputDbName = QtGui.QLineEdit(self.widAddDB)
        self.inputDbName.setGeometry(QtCore.QRect(450, 130, 291, 27))
        self.inputDbName.setObjectName("inputDbName")
        self.labelImport = QtGui.QLabel(self.widAddDB)
        self.labelImport.setGeometry(QtCore.QRect(80, 200, 321, 21))
        self.labelImport.setObjectName("labelImport")
        self.labelProcess = QtGui.QLabel(self.widAddDB)
        self.labelProcess.setGeometry(QtCore.QRect(460, 520, 191, 21))
        self.labelProcess.setObjectName("labelProcess")
        self.widAddDB.hide()
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2188, 31))
        self.menubar.setMouseTracking(True)
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def changeToCompare(self):
        self.widMainMenu.hide()
        self.widCompare.show()

    def changeToAdd(self):
        self.widMainMenu.hide()
        self.widAddDB.show()

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDatabase.setText(QtGui.QApplication.translate("mainWindow", "Base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFiles.setText(QtGui.QApplication.translate("mainWindow", "Archivos", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDownload.setText(QtGui.QApplication.translate("mainWindow", "Descargar", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCompare.setText(QtGui.QApplication.translate("mainWindow", "Comparar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Ingrese la secuencia a comparar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Cantidad de resultados", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMenuEdit.setText(QtGui.QApplication.translate("mainWindow", "Editar Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMenuCompare.setText(QtGui.QApplication.translate("mainWindow", "Comparar Secuencias", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMenuDelete.setText(QtGui.QApplication.translate("mainWindow", "Eliminar base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMenuAdd.setText(QtGui.QApplication.translate("mainWindow", "Agregar Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonImport.setText(QtGui.QApplication.translate("mainWindow", "Importar", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDbName.setText(QtGui.QApplication.translate("mainWindow", "Ingrese el nombre de la nueva base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.labelImport.setText(QtGui.QApplication.translate("mainWindow", "Importar desde una carpeta de archivos", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProcess.setText(QtGui.QApplication.translate("mainWindow", "Importando archivos", None, QtGui.QApplication.UnicodeUTF8))

